# Generated by Django 5.0.3 on 2024-06-19 23:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Boleta",
            fields=[
                ("boleta_id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("metodo_pago", models.CharField(max_length=45)),
                ("transaccion_id", models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=45, unique=True)),
                ("email", models.EmailField(max_length=45)),
                ("password", models.CharField(max_length=128)),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[("cliente", "Cliente"), ("prestador", "Prestador")],
                        max_length=50,
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Comuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("poblacion", models.CharField(max_length=255)),
                ("area", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                ("genero_id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=45)),
                ("descripcion", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                ("servicio_id", models.AutoField(primary_key=True, serialize=False)),
                ("duracion_serv", models.TimeField()),
                ("nombre_serv", models.CharField(max_length=100)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("metodo_pago", models.CharField(max_length=100)),
                (
                    "foto",
                    models.CharField(
                        default="Descripción no proporcionada", max_length=1000
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        default="Descripción no proporcionada", max_length=200
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cita",
            fields=[
                ("cita_id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_hora", models.DateTimeField()),
                ("duracion", models.TimeField()),
                (
                    "boleta",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cita_cita",
                        to="api.boleta",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="boleta",
            name="cita",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boleta_boletas",
                to="api.cita",
            ),
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "usuario_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.usuario",
                    ),
                ),
                ("img", models.CharField(max_length=350)),
                ("puntos", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("api.usuario",),
        ),
        migrations.CreateModel(
            name="PrestadorServicios",
            fields=[
                (
                    "usuario_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.usuario",
                    ),
                ),
                ("especialidad", models.CharField(max_length=350)),
                ("experiencia", models.CharField(max_length=450)),
                ("presentacion", models.CharField(max_length=200)),
                (
                    "calificacion",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("api.usuario",),
        ),
        migrations.CreateModel(
            name="HistorialCompra",
            fields=[
                ("hist_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "calificacion",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "boleta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.boleta"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Local",
            fields=[
                ("local_id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "comuna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locales",
                        to="api.comuna",
                    ),
                ),
                (
                    "prestador",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local",
                        to="api.prestadorservicios",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cita",
            name="local",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.local"
            ),
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                ("persona_id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_nac", models.DateField()),
                ("nombre", models.CharField(max_length=55)),
                ("apellido1", models.CharField(max_length=30)),
                ("apellido2", models.CharField(max_length=30)),
                (
                    "genero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.genero"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonaUsuario",
            fields=[
                (
                    "persona_user_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.persona"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.usuario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("prod_id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_prod", models.CharField(max_length=100)),
                (
                    "foto",
                    models.CharField(
                        default="Imagen no proporcionada", max_length=1000
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=0)),
                ("a_la_venta", models.BooleanField(default=False)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "descripcion",
                    models.TextField(
                        default="Descripción no proporcionada", max_length=200
                    ),
                ),
                ("sku_id", models.CharField(max_length=50)),
                (
                    "local",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.local",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cita",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.cliente"
            ),
        ),
        migrations.CreateModel(
            name="ServicioAPrestar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarifa", models.DecimalField(decimal_places=2, max_digits=10)),
                ("disponibilidad", models.CharField(max_length=150)),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.local"
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.servicio"
                    ),
                ),
                (
                    "prestador_serv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.prestadorservicios",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cita",
            name="prestador_serv",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.prestadorservicios"
            ),
        ),
    ]
