# Generated by Django 5.0.3 on 2024-06-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comuna",
            name="poblacion",
            field=models.CharField(max_length=255),
        ),
    ]
