from django.urls import path
from .views import *

urlpatterns = [
    path('usuarios/cliente/registro/',
         registrar_usuario_cliente, name='registro_cliente'),
    path('usuarios/prestador/registro/',
         registrar_usuario_prestador, name='registro_prestador'),
    path('usuarios/login/', iniciar_sesion, name='iniciar_sesion'),
    path('usuarios/<int:usuario_id>/', obtener_usuario, name='obtener_usuario'),
    path('usuarios/<int:usuario_id>/actualizar/',
         actualizar_usuario, name='actualizar_usuario'),
    path('usuarios/<int:usuario_id>/eliminar/',
         eliminar_usuario, name='eliminar_usuario'),
    path('agendar_cita/', agendar_cita, name='agendar_cita'),
    path('retrasar_cita/<int:cita_id>/', retrasar_cita, name='retrasar_cita'),
    path('clientes/<int:cliente_id>/citas/',
         obtener_citas_cliente, name='obtener_citas_cliente'),
    path('clientes/<int:cliente_id>/historial/',
         ver_historial_compras, name='ver_historial_compras'),
    path('prestadores/<int:prestador_id>/citas/',
         obtener_citas_prestador, name='obtener_citas_prestador'),
    path('productos/', listar_productos, name='listar_productos'),
    path('productos/agregar/', agregar_producto, name='agregar_producto'),
    path('productos/<int:producto_id>/actualizar/',
         actualizar_producto, name='actualizar_producto'),
    path('productos/<int:producto_id>/eliminar/',
         eliminar_producto, name='eliminar_producto'),
    path('productos/<int:producto_id>/',
         obtener_producto, name='obtener_producto'),
    path('locales/', obtener_locales, name='obtener_locales'),
    path('locales/crear/', crear_local, name='crear_local'),
    path('locales/<int:local_id>/actualizar/',
         actualizar_local, name='actualizar_local'),
    path('locales/<int:local_id>/eliminar/',
         eliminar_local, name='eliminar_local'),
    path('locales/<int:local_id>/', obtener_local, name='obtener_local'),
    path('locales/<int:local_id>/productos/',
         obtener_productos_por_local, name='obtener_productos_por_local'),
    path('locales/<int:local_id>/inventarios/',
         listar_inventarios_por_local, name='listar_inventarios_por_local'),
    path('inventarios/agregar/', agregar_inventario, name='agregar_inventario'),
    path('inventarios/<int:inventario_id>/actualizar/',
         actualizar_inventario, name='actualizar_inventario'),
    path('inventarios/<int:inventario_id>/eliminar/',
         eliminar_inventario, name='eliminar_inventario'),
    path('inventarios/<int:inventario_id>/productos/',
         obtener_productos_por_inventario, name='obtener_productos_por_inventario'),
    path('inventarios/<int:inventario_id>/detalle/',
         obtener_inventario_detalle, name='obtener_inventario_detalle'),
    path('serviciosaprestar/por-local/<int:local_id>/',
         listar_servicios_por_local, name='listar_servicios_por_local'),
    path('servicioaprestar/', listar_servicios_aprestar,
         name='listar_servicios_aprestar'),
    path('servicioaprestar/crear/', crear_servicio_aprestar,
         name='crear_servicio_aprestar'),
    path('servicioaprestar/<int:id>/', obtener_servicio_aprestar,
         name='obtener_servicio_aprestar'),
    path('servicioaprestar/<int:id>/actualizar/',
         actualizar_servicio_aprestar, name='actualizar_servicio_aprestar'),
    path('servicioaprestar/<int:id>/eliminar/',
         eliminar_servicio_aprestar, name='eliminar_servicio_aprestar'),
    path('compras/realizar/', realizar_compra, name='realizar_compra'),
    path('comunas/', listar_comunas, name='listar_comunas'),
    path('servicios/', listar_servicios, name='listar_servicios'),
    path('servicios/crear/', crear_servicio, name='crear_servicio'),
    path('servicios/<int:servicio_id>/',
         obtener_servicio, name='obtener_servicio'),
    path('servicios/por-local/<int:local_id>/',
         obtener_servicios_por_local, name='obtener_servicios_por_local'),
    path('servicios/por-servicioaprestar/<int:servicioaprestar_id>/',
         obtener_servicios_por_servicioaprestar, name='obtener_servicios_por_servicioaprestar'),
    path('servicios/<int:servicio_id>/actualizar/',
         actualizar_servicio, name='actualizar_servicio'),
    path('servicios/<int:servicio_id>/eliminar/',
         eliminar_servicio, name='eliminar_servicio'),
]
